services:
  recco-server:
    image: recco-server
    container_name: recco-server
    volumes:
      - ./recco-server:/recco-server
    ports:
      - "8080:8080"
    build:
      dockerfile: recco-server.Dockerfile
      tags:
        - "recco-server"
    tty: true
  recco-db:
    image: qdrant/qdrant:v1.13.6
    container_name: recco-db
    ports:
      - "6333:6333"
    tty: true

      
