services:
  recco-lb:
    image: recco-lb
    build:
      context: ./recco-lb/
      dockerfile: recco-lb.Dockerfile
    container_name: recco-lb
    environment:
      - RECCO_IP
      - RECCO_SERVER_PORT
      - RECCO_EMBED_PORT
      - RECCO_DB_PORT
    volumes:
      - ./recco-lb/nginx:/recco-lb
    ports:
      - "${RECCO_LB_PORT}:80"
    tty: true
    depends_on:
      recco-server:
        condition: service_started
      recco-embed:
        condition: service_healthy
      recco-db:
        condition: service_started

  recco-server:
    image: recco-server
    build:
      context: ./recco-server/
      dockerfile: recco-server.Dockerfile
    container_name: recco-server
    environment:
      - RECCO_IP
      - RECCO_EMBED_PORT
      - RECCO_DB_PORT
    volumes:
      - ./recco-server/code:/recco-server
    ports:
      - "${RECCO_SERVER_PORT}:80"
    tty: true

  recco-embed:
    image: recco-embed
    build:
      context: ./recco-embed/
      dockerfile: recco-embed.Dockerfile
    container_name: recco-embed
    environment:
      - HOST=${RECCO_IP}
      - MODEL_ID=${EMBEDDING_MODEL}
    volumes:
      - ./recco-embed/data:/data
    ports:
      - "${RECCO_EMBED_PORT}:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    tty: true

  recco-db:
    image: recco-db
    build:
      context: ./recco-db/
      dockerfile: recco-db.Dockerfile
    container_name: recco-db
    environment:
      - RUN_MODE=development
    volumes:
      - ./recco-db/dev-data/dev-config:/qdrant/config
      - ./recco-db/dev-data/dev-storage:/qdrant/storage
    ports:
      - "${RECCO_DB_PORT}:6333"
    tty: true
    depends_on:
      recco-embed:
        condition: service_healthy

  recco-db-load:
    image: recco-db-load
    build:
      context: ./recco-db-load/
      dockerfile: recco-db-load.Dockerfile
    container_name: recco-db-load
    environment:
      - RECCO_IP=${RECCO_IP}
      - RECCO_LB_PORT=${RECCO_LB_PORT}
      - MOVIE_TITLES_EMBEDDING_DIM=${MOVIE_TITLES_EMBEDDING_DIM}
      - MOVIE_RATINGS_EMBEDDING_DIM=${MOVIE_RATINGS_EMBEDDING_DIM}
    volumes:
      - ./recco-db-load/dataset:/app/dataset
    depends_on:
      recco-lb:
        condition: service_started
