services:
  recco-lb:
    image: recco-lb
    build:
      context: ./recco-lb/
      dockerfile: recco-lb.Dockerfile
    container_name: recco-lb
    environment:
      - RECCO_IP
      - RECCO_SERVER_PORT
      - RECCO_EMBED_PORT
      - RECCO_DB_PORT
    volumes:
      - ./recco-lb/nginx:/recco-lb
    ports:
      - "${RECCO_LB_PORT}:80"
    tty: true

  recco-server:
    image: recco-server
    build:
      context: ./recco-server/
      dockerfile: recco-server.Dockerfile
    container_name: recco-server
    environment:
      - RECCO_IP
      - RECCO_EMBED_PORT
      - RECCO_DB_PORT
    volumes:
      - ./recco-server/code:/recco-server
    ports:
      - "${RECCO_SERVER_PORT}:80"
    tty: true

  recco-embed:
    image: recco-embed
    build:
      context: ./recco-embed/
      dockerfile: recco-embed.Dockerfile
    container_name: recco-embed
    environment:
      - HOST=${RECCO_IP}
    volumes:
      # If missing, load data by running start.sh -d
      - ./recco-embed/data:/data
    ports:
      - "${RECCO_EMBED_PORT}:80"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    tty: true

  recco-db:
    image: recco-db
    build:
      context: ./recco-db/
      dockerfile: recco-db.Dockerfile
    container_name: recco-db
    environment:
      - RUN_MODE=development
    volumes:
      - ./recco-db/dev-data/dev-config:/qdrant/config
      # If missing, get data by runing start.sh -d
      - ./recco-db/dev-data/dev-storage:/qdrant/storage
    ports:
      - "${RECCO_DB_PORT}:6333"
    tty: true 
